### ISSUE TITLE
[Proposal] New features

### ISSUE THREAD

**Issue by fmunteanu** [PowerDataHub/terraform-aws-airflow#21]
I installed your module, thank you for making everyone's life easy, deploying Airflow with Terraform. 😄

At Expedia, we need few specific variables to be added. We need be able to:
- define custom subnets, AZs (#19) and security groups
- be able to use an AWS console existing ssh key (instead of creating a fresh one)
- restrict IAM role permissions (current permissions could allow an user logged into EC2 to delete all buckets, instead of being restricted to the one created by Terraform)
- use custom tags we can define, for all Terraform resources
- use SSL for Admin UI and Flower
- use LDAP authentication for Admin UI (admin, user, read_only, etc.)

I would like to contribute to the code with all these features, which should be useful to other people. How do you want me to approach this? Should I clone the master and create a branch to be evaluated by your contributors?

**Comment by edbizarro** [comment]
Hi @fmunteanu 

wow, I'd be very happy with all those contributions, would be very nice.

About the approach, I'd recommend creating feature-specific branches and submit one PR for feature, that way the review process will be much easier.

And about that issue #19 support for AZ's are half-implemented, I'll look at this tomorrow morning, I believe it won't be so hard to finish.

**Comment by fmunteanu** [comment]
@edbizarro can I can create for example a `feature/custom-subnet` branch and submit the PR directly to your master or you prefer I fork the project?

**Comment by edbizarro** [comment]
A fork and PR

**Comment by fmunteanu** [comment]
@edbizarro I was wondering if we could keep this issue open and inform you on what I currently plan to add into each branch. GH-24 was the most urgent, to add custom tags. Now that resources are properly tagged, they will not be deleted anymore in our AWS environments.

Next, I want to work on implementing application/network load balancers and autoscaling groups. I will also implement a Route 53 Recordset group aliased to load balancer with an SSL certificate, so we secure the communication. I plan to enable SSL for all components, we can automatically generate AWS self-signed certificates or use existing wildcard public certificates.

**Comment by edbizarro** [comment]
Sure!

**Comment by edbizarro** [comment]
Release [v0.8.14](https://github.com/PowerDataHub/terraform-aws-airflow/releases/tag/v0.8.14) published with custom tags support. Thanks @fmunteanu for this awesome contribution!

**Comment by fmunteanu** [comment]
@edbizarro quick question, what determined you to use the `terraform-terraform-label` module, instead of `terraform-null-label`?

**Comment by edbizarro** [comment]
actually, I didn't know about the `terraform-null-label` module, I bumped into this `terraform-terraform-label` module by accident and found useful.

**Comment by fmunteanu** [comment]
After looking at [autoscaling](https://registry.terraform.io/modules/terraform-aws-modules/autoscaling/aws) module, we can use `terraform-terraform-label`. I plan to use [Goofys](https://github.com/kahing/goofys) to mount the `/usr/local/airflow/dags` directory, it will sync the DAGs across all autoscaled resources. I already looked in the past and adopted it, Goofys is the most performant fuse mount.

Mount example into `/etc/fstab`:
```
goofys#bucket-name  /usr/local/airflow/dags  fuse  _netdev,allow_other,nonempty,--no-implicit-dir,--gid=1000,--uid=1000  0 0
```

**Comment by edbizarro** [comment]
Nice! I didn't know about these 'S3 mount' but seems very useful.

One thing to keep in mind is that the provisioning script generates a new fernet key every time, on new clusters this is fine (generate 1 time per machine) because there is nothing on the metadata db, but for ASG the process needs to be more sophisticated, maybe store the fernet key on those S3 mount volume and on the script's run we check if there already have one generated key and skip this step, otherwise all the encrypted connections and variables will be unaccessible.

I'll think about this and come up with something to working on that front.

**Comment by fmunteanu** [comment]
@edbizarro can you detail more about the fernet key? We can edit the `airflow.service` configuration file to do a pre-check. I'm not a fan of UserData scripts, I prefer having everything done as service validated by systemd.

**Comment by fmunteanu** [comment]
@edbizarro, I created GH-27 for custom CIDRs.

**Comment by edbizarro** [comment]
> @edbizarro can you detail more about the fernet key? We can edit the `airflow.service` configuration file to do a pre-check. I'm not a fan of UserData scripts, I prefer having everything done as service validated by systemd.

But in this case, how do you suggest that we handle the provisioning?

Today we have a [provisioning script](https://github.com/PowerDataHub/terraform-aws-airflow/blob/master/files/cloud-init.sh) that runs in the cloud-init, and in that script we generate a fernet-key and save it as ENV for airflow (used for encrypting connections and variables)

**Comment by fmunteanu** [comment]
@edbizarro I'm in the process of rewriting that script through `cloud-config`, here it is a portion of `webserver.tf`:
```
data "template_cloudinit_config" "webserver" {
  gzip = false
  base64_encode = false
  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.webserver.rendered}"
  }
}

data "template_file" "webserver" {
  template = "${file("${path.module}/files/webserver.tpl")}"
  vars {
    S3 = "${module.airflow_labels.id}"
  }
}

resource "aws_launch_configuration" "webserver" {
  image_id = "${var.ami}"
  instance_type = "${var.webserver_instance_type}"
  name = "${module.airflow_labels_webserver.id}-lc"
  # TODO: create EBS varibles as String
  ebs_block_device {
    device_name = "${var.ebs_device_name}"
    volume_type = "${var.ebs_volume_type}"
    volume_size = "${var.ebs_volume_size}"
    delete_on_termination = "${var.ebs_volume_delete_on_termination}"
  }
  lifecycle {
    create_before_destroy = true
  }
  user_data = "${data.template_cloudinit_config.webserver.rendered}"
}
```
And `webserver.tpl`:
```
#cloud-config
# vim: syntax=yaml

package_upgrade: true

packages:
  - freetds-dev
  - git

users:
  - default
  - name: airflow
    gecos: Airflow
    system: true

write_files:
  - content: |
      LABEL=cloudimg-rootfs  /  ext4  defaults,discard,noatime  0 0
      goofys#S3  /var/lib/airflow  fuse  _netdev,allow_other,nonempty,--no-implicit-dir,--gid=999,--uid=999  0 0
    owner: root:root
    path: /etc/fstab
    permissions: '0644'

runcmd:
  - [ install, -dg, airflow, -o, airflow, -m, 0755, /var/lib/airflow ]
  - [ wget, https://github.com/kahing/goofys/releases/download/v0.20.0/goofys, -O, /usr/local/bin/goofys ]
  - [ chmod, 0755, /usr/local/bin/goofys ]
```

I plan to add all your script, but install only what each components needs, in this case the webserver. Do you have a Slack channel I can join, so we can talk easier?

**Comment by fmunteanu** [comment]
@edbizarro I have a block on https://github.com/terraform-aws-modules/terraform-aws-alb/issues/111. Do you have any suggestions?

**Comment by edbizarro** [comment]
I'll take a look at it

**Comment by edbizarro** [comment]
Hi @fmunteanu are you still working on theses improvs? Love to hear what are working now and If I can help

**Comment by fmunteanu** [comment]
We actually changed direction and using Airflow with Kubernetes Executor.
