### ISSUE TITLE
Bumping Terraform version to 0.12?

### ISSUE THREAD

**Issue by fmunteanu** [PowerDataHub/terraform-aws-airflow#30]
This will allow us we can start using HCL2 expressions and clean a lot the code.

**Comment by edbizarro** [comment]
Yeah, I've done that and tag a new version

Terraform v0.12 = v0.8.15
Terraform v0.11 = v0.7.x

**Comment by fmunteanu** [comment]
@edbizarro should I start cleaning up the code for the branch I work on?

**Comment by edbizarro** [comment]
@fmunteanu Sure! That'll be great.

Just update your branch with the last changes from master and you're good to go.

The terraform docs have a section about the module structure, this can be helpful https://www.terraform.io/docs/modules/index.html#standard-module-structure

**Comment by edbizarro** [comment]
I clean up some files and ran 0.12upgrade
