### ISSUE TITLE
Inherit provider settings from parent

### ISSUE THREAD

**Issue by jozsi** [PowerDataHub/terraform-aws-airflow#34]
Hello,

The module seems to be explicitly defining the provider and does not inherit it from the parent/root module. This limits the user of only being able to configure the region and does not allow, for example, static credentials.

I've deleted the `provider.tf` from the module to get around this, however, I wonder if there are more elegant solutions.

Thank you!

**Comment by edbizarro** [comment]
Yeah you're right, there is no reason for this file, I've removed and tagged a new version

**Comment by jozsi** [comment]
Thank you, @edbizarro !
