### ISSUE TITLE
Scheduler number of runs

### ISSUE THREAD

**Issue by jozsi** [PowerDataHub/terraform-aws-airflow#35]
Hi,

I noticed that the scheduler has [number of runs set to 10](https://github.com/PowerDataHub/terraform-aws-airflow/blob/master/files/cloud-init.sh#L77).

What was the reason for this? To pick up new DAG files? Cause for that, as far as I understood, `dag_dir_list_interval` does that automatically every 300 seconds by default.

**Comment by edbizarro** [comment]
This flag makes the scheduler process restart after n runs to avoid weird behaviors

**Comment by jozsi** [comment]
What are those weird behaviors? Do they still happen with the latest version of Airflow?

**Comment by edbizarro** [comment]
@jozsi scheduler hanging and not scheduling new tasks, but i don't know If still happen with current version

**Comment by edbizarro** [comment]
Ref: https://issues.apache.org/jira/plugins/servlet/mobile#issue/AIRFLOW-401

**Comment by jozsi** [comment]
Ouch, I see a recent comment reporting that the bug still exists in v1.10.4 (dated august 2019; latest is v1.10.7), 3+ years since it has been reported. Hence the workaround is still valid, the only minor drawback could be that it fills up the logs.
